### ISSUE TITLE
Refactor parse/lex/eval to use a very simple API

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/llama#22]
parse() should take a string and do parsing, with no explicit lexer, mocks, and with optimize=1

**Comment by dionyziz** [comment]
```
from llama import parse

parse("let a = 5")
```

**Comment by Renelvon** [comment]
Suppose an error happens during parsing. How should that be reported?

**Comment by dionyziz** [comment]
If a logger is passed, through that logger. Otherwise, on stderr if non-fatal, or through an exception if fatal.
