### ISSUE TITLE
Even simpler API

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/llama#51]
Make the following work:

```
from compiler import parse
parse.parse("int ref ref", "type")
```

**Comment by Renelvon** [comment]
The `parse` function accepts a data string and an optional `logger`. So, the best I can do is add another optional argument `start` and have:

```
from compiler import parse
parse.parse("int ref ref", start="type")
```

Would that be ok?

**Comment by dionyziz** [comment]
Yes, but let's move the logger argument to be third so that start parameter
doesn't have to be named.

**Comment by Renelvon** [comment]
OK.
